// Auto-generated by ptx2cpp.py — do not edit
#pragma once
#include <cstdint>
#include <cuda_runtime.h>

extern "C" void softmax_launch(
    uint64_t param_0,
    uint64_t param_1,
    uint32_t param_2,
    uint32_t param_3,
    dim3 grid,
    dim3 block);

void softmax_launch(
    const void* param_0,
    const void* param_1,
    uint32_t param_2,
    uint32_t param_3,
    dim3 grid,
    dim3 block);
