// Auto-generated by ptx2cpp.py — do not edit
#pragma once
#include <cstdint>
#include <cuda_runtime.h>

extern "C" void relu_launch(
    uint64_t param_0,
    uint32_t param_1,
    dim3 grid,
    dim3 block);

void relu_launch(
    const void* param_0,
    uint32_t param_1,
    dim3 grid,
    dim3 block);

extern "C" void leaky_relu_launch(
    uint64_t param_0,
    float param_1,
    uint32_t param_2,
    dim3 grid,
    dim3 block);

void leaky_relu_launch(
    const void* param_0,
    float param_1,
    uint32_t param_2,
    dim3 grid,
    dim3 block);

extern "C" void float_to_int_launch(
    uint64_t param_0,
    uint64_t param_1,
    uint32_t param_2,
    dim3 grid,
    dim3 block);

void float_to_int_launch(
    const void* param_0,
    const void* param_1,
    uint32_t param_2,
    dim3 grid,
    dim3 block);
