// Auto-generated by ptx2cpp.py — do not edit
#pragma once
#include <cstdint>
#include <cuda_runtime.h>

extern "C" void saxpy_launch(
    uint32_t param_0,
    float param_1,
    uint64_t param_2,
    uint64_t param_3,
    dim3 grid,
    dim3 block);

void saxpy_launch(
    uint32_t param_0,
    float param_1,
    const void* param_2,
    const void* param_3,
    dim3 grid,
    dim3 block);

extern "C" void saxpy_launch_generic(void** args,
    uint32_t gx, uint32_t gy, uint32_t gz,
    uint32_t bx, uint32_t by, uint32_t bz,
    uint32_t shared_bytes);
