// saxpy on CPU via cuda_sim — identical to real CUDA host code
#include <cstdio>
#include <cuda_runtime.h>
#include "kernel_cpu.h"  // generated by ptx2cpp.py

int main() {
    float x[] = {1,2,3,4,5,6,7,8}, y[] = {10,20,30,40,50,60,70,80};
    float *d_x, *d_y;
    cudaMalloc((void**)&d_x, sizeof(x));
    cudaMalloc((void**)&d_y, sizeof(y));
    cudaMemcpy(d_x, x, sizeof(x), cudaMemcpyHostToDevice);
    cudaMemcpy(d_y, y, sizeof(y), cudaMemcpyHostToDevice);

    saxpy<<<1, 8>>>(8, 2.0f, d_x, d_y);  // y = 2*x + y

    cudaMemcpy(y, d_y, sizeof(y), cudaMemcpyDeviceToHost);
    cudaFree(d_x);
    cudaFree(d_y);

    for (int i = 0; i < 8; i++) printf("%.0f ", y[i]);
    printf("\n");
    // Output: 12 24 36 48 60 72 84 96
}
